name: Build Images
on:
  workflow_dispatch:

env:
  IMG_URL: "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-11/2023-12-11-raspios-bookworm-arm64-lite.img.xz"
  MD5_URL: "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-11/2023-12-11-raspios-bookworm-arm64-lite.img.xz.sha256"
  FILENAME: "raspios-lite-arm64.img"

jobs:
  build-raspios:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `go`
        uses: actions/setup-go@v2.1.3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
      
      - name: Get `packer-build-arm` plugin
        run: |-
          git clone https://github.com/mkaczanowski/packer-builder-arm plugin
          cd plugin
          go mod download
          go build
          cp packer-builder-arm ..

      - name: Run `packer build`
        id: build
        run: "packer build raspios-lite.json"
        
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          path: '*.img'
