name: Build Images
on:
  workflow_dispatch:

env:
  IMG_URL: "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-11/2023-12-11-raspios-bookworm-arm64-lite.img.xz"
  MD5_URL: "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-11/2023-12-11-raspios-bookworm-arm64-lite.img.xz.sha256"
  FILENAME: "raspios-lite-arm64.img"

jobs:
  build-raspios:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer build`
        id: build
        run: "build raspios-lite.json"
        
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          path: '*.img'
